spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

security:
  jwt:
    token:
      secret-key:
      expire-length:

shopping:
  admin:
    email:
    nickname:
    password: